// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdFuNPrLRjAwqOfueAI0p78C1e2B99Mk',
    appId: '1:397212126520:web:b758382229187af77445cd',
    messagingSenderId: '397212126520',
    projectId: 'payrent-business',
    authDomain: 'payrent-business.firebaseapp.com',
    storageBucket: 'payrent-business.firebasestorage.app',
    measurementId: 'G-8RWY9NM8HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdFuNPrLRjAwqOfueAI0p78C1e2B99Mk',
    appId: '1:397212126520:android:b758382229187af77445cd',
    messagingSenderId: '397212126520',
    projectId: 'payrent-business',
    authDomain: 'payrent-business.firebaseapp.com',
    storageBucket: 'payrent-business.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdFuNPrLRjAwqOfueAI0p78C1e2B99Mk',
    appId: '1:397212126520:ios:b758382229187af77445cd',
    messagingSenderId: '397212126520',
    projectId: 'payrent-business',
    authDomain: 'payrent-business.firebaseapp.com',
    storageBucket: 'payrent-business.firebasestorage.app',
    iosBundleId: 'com.example.payrentBusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZdFuNPrLRjAwqOfueAI0p78C1e2B99Mk',
    appId: '1:397212126520:ios:b758382229187af77445cd',
    messagingSenderId: '397212126520',
    projectId: 'payrent-business',
    authDomain: 'payrent-business.firebaseapp.com',
    storageBucket: 'payrent-business.firebasestorage.app',
    iosBundleId: 'com.example.payrentBusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZdFuNPrLRjAwqOfueAI0p78C1e2B99Mk',
    appId: '1:397212126520:web:b758382229187af77445cd',
    messagingSenderId: '397212126520',
    projectId: 'payrent-business',
    authDomain: 'payrent-business.firebaseapp.com',
    storageBucket: 'payrent-business.firebasestorage.app',
    measurementId: 'G-8RWY9NM8HQ',
  );
}